# Generated by Django 6.0.1 on 2026-01-08 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_name', models.CharField(help_text='e.g. competitor-selection', max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('tags', models.JSONField(blank=True, default=dict, help_text='Metadata like version, region')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=255)),
                ('step_type', models.CharField(choices=[('LLM', 'LLM Call'), ('FILTER', 'Filtering Logic'), ('API', 'External API'), ('RANK', 'Ranking Algo'), ('DECISION', 'Final Decision')], default='FILTER', max_length=20)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.pipelinerun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
